package:
  name: gpyfft
  version: 0.7.1

about:
  home: https://github.com/geggo/gpyfft
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: Python wrapper for the OpenCL FFT library clFFT

source:
  git_url: https://github.com/geggo/gpyfft
  git_rev: 3ed258f2ec2a2e6b4157e00d071bd861a0f42afd

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - clfft
    - pyopencl
  run:
    - python
    - clfft
    - pyopencl
    - numpy

test:
  requires:
    - nose-parameterized